// webpack_react/src/pages/Home.jsx
import React from 'react';
import { Carousel, Row, Col, Card } from 'antd';
import { get } from '@/Api';

class Home extends React.Component {
    state = {
        adv_list: [],
        datalist: []
    }
    async componentDidMount() {
        let { datas } = await get({
            act: 'index'
        });
        // console.log(datas);
        this.setState({
            adv_list: datas[0].adv_list.item
        })
        // console.log(this.state.adv_list);
        // 首页数据
        let datalist = datas.slice(1).map(item => item.goods);

        this.setState({
            datalist
        })
    }
    goto = (id) => {
        let { history } = this.props
        history.push(`/goods/${id}`);
    }
    render() {
        let { adv_list, datalist } = this.state
        return (
            <div>
                <div>
                    <Carousel  >
                        {
                            adv_list.map(item => {
                                return <div>
                                    <img src={item.image} style={{ width: '100%', maxHeight: 150 }} alt="" />
                                </div>
                            })
                        }

                    </Carousel>
                </div>
                <div>
                    {
                        datalist.map(item => {
                            return <div style={{ marginBottom: 24 }}>
                                <h4>{item.title}</h4>
                                <Row type="flex" >
                                    {
                                        item.item.map(item => {
                                            return <Col span={12} onClick={this.goto.bind(this, item.goods_id)}>
                                                <Card
                                                    hoverable
                                                    style={{ width: 200 }}
                                                    cover={<img alt="example" src={item.goods_image} />}
                                                >
                                                    <Card.Meta title={item.goods_name} description={item.goods_price} />
                                                </Card>
                                            </Col>
                                        })
                                    }
                                </Row>
                            </div>
                        })
                    }
                </div>

            </div>
        )
    }
}
export default Home;

// w2_VueRouter/myapp/src/pages/Home.vue
<template>
  <div>
    <el-carousel height="200px">
      <el-carousel-item v-for="item in adlist" :key="item.data">
        <img :src="item.image" style="width:100%" />
      </el-carousel-item>
    </el-carousel>

    <div v-for="category in recommend" :key="category.title">
      <h4>{{category.title}}</h4>
      <el-row :gutter="20">
        <el-col
          :span="6"
          v-for="item in category.item"
          :key="item.goods_id"
          style="height:360px"
          @click.native="goto(item.goods_id)"
        >
          <el-image style="width:100%" :src="item.goods_image" fit="contain"></el-image>
          <h4>{{item.goods_name}}</h4>
          <p class="price">
            <del>{{item.goods_price}}</del>
            <span>{{item.goods_promotion_price}}</span>
          </p>
        </el-col>
      </el-row>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      adlist: [],
      recommend: []
    };
  },
  methods: {
    goto(id) {
      //   this.$router.push(`/goods/${id}`);
      this.$router.push({ name: "goods", params: { id } });
    }
  },
  async created() {
    // 发起ajax请求
    let {
      data: { datas }
    } = await this.$axios.get("https://www.nanshig.com/mobile/index.php", {
      params: {
        act: "index"
      }
    });

    // 轮播图数据
    this.adlist = datas[0].adv_list.item;

    // 春夏新品推荐
    this.recommend = datas.slice(1).map(item => {
      return item.goods;
    }); //[{title,item},{},{},{}]
  },
  beforeRouteLeave(to, from, next) {
    console.log("Home.beforeRouteLeave");
    next();
  }
};
</script>
<style lang="scss" scoped>
</style>
